-- Per-equity-rank-group metric tracking: er1..er6 (see src/equity_groups.py
-- for the group registry, and API_REQUIREMENTS.md §1.1a for why these exist
-- alongside v1/v2). Each of Denver DOTI's six EquityGroupRank tiers
-- (1 = highest need) gets the same total/percent fields as v1/v2 in BOTH
-- the per-cycle 22-metric snapshot and the 6am-9am daily SLA average, so
-- a future compliance cutoff can be reconstructed from history (e.g.
-- rank<=2 = er1 + er2) without having had to guess the combination up
-- front.
--
-- Deliberately NO compliance_erN_pass boolean: no individual rank tier is
-- itself a compliance boundary, so there's nothing to pass/fail on its
-- own. The frontend combines whichever er-groups make up a candidate
-- cutoff and computes pass/fail itself from the avg_percent_all_devices_erN
-- values below. compliance_v1_pass / compliance_v2_pass (existing columns)
-- remain the only stored pass/fail flags.

ALTER TABLE snapshot_metadata_core
    ADD COLUMN IF NOT EXISTS total_devices_er1            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er1               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er1            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er1      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er1        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er1     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er1            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er1         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS total_devices_er2            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er2               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er2            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er2      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er2        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er2     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er2            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er2         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS total_devices_er3            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er3               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er3            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er3      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er3        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er3     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er3            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er3         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS total_devices_er4            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er4               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er4            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er4      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er4        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er4     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er4            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er4         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS total_devices_er5            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er5               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er5            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er5      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er5        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er5     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er5            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er5         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS total_devices_er6            INTEGER,
    ADD COLUMN IF NOT EXISTS total_bike_er6               INTEGER,
    ADD COLUMN IF NOT EXISTS total_scooter_er6            INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_devices_er6      NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_bikes_er6        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_scooters_er6     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_bikes_er6            NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_scooters_er6         NUMERIC(5,2);

ALTER TABLE daily_sla_compliance
    ADD COLUMN IF NOT EXISTS avg_total_devices_er1        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er1           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er1        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er1  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er1    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er1 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er1        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er1     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_total_devices_er2        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er2           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er2        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er2  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er2    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er2 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er2        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er2     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_total_devices_er3        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er3           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er3        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er3  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er3    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er3 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er3        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er3     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_total_devices_er4        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er4           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er4        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er4  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er4    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er4 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er4        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er4     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_total_devices_er5        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er5           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er5        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er5  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er5    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er5 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er5        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er5     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_total_devices_er6        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_bike_er6           NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_scooter_er6        NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_devices_er6  NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_bikes_er6    NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_scooters_er6 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_bikes_er6        NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_scooters_er6     NUMERIC(5,2);
