-- Compliance-stat parity for the vehicle_use_type dimension (sitting vs
-- standing), mirroring the existing form_factor (bicycle vs scooter)
-- split exactly, for every tracked equity group (v1, v2, er1..er6) plus
-- citywide. See src/equity_groups.py SPLIT_DIMENSIONS for the
-- generalization that computes both dimensions, and
-- sql/016_vehicle_classification.sql for the underlying
-- vehicle_use_type column this is derived from.
--
-- Deliberately mirrors sql/015's shape: totals as INTEGER (snapshot) /
-- NUMERIC(10,2) (daily average), percents as NUMERIC(5,2) throughout.

ALTER TABLE snapshot_metadata_core
    ADD COLUMN IF NOT EXISTS total_sitting_denver             INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_denver            INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_v1                 INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_v1                INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_v2                 INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_v2                INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er1                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er1               INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er2                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er2               INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er3                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er3               INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er4                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er4               INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er5                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er5               INTEGER,
    ADD COLUMN IF NOT EXISTS total_sitting_er6                INTEGER,
    ADD COLUMN IF NOT EXISTS total_standing_er6               INTEGER,
    ADD COLUMN IF NOT EXISTS percent_all_sitting_v1           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_v1          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_v2           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_v2          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er1          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er1         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er2          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er2         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er3          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er3         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er4          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er4         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er5          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er5         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_sitting_er6          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_all_standing_er6         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_denver           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_denver          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_v1               NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_v1              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_v2               NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_v2              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er1              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er1             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er2              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er2             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er3              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er3             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er4              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er4             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er5              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er5             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_sitting_er6              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS percent_standing_er6             NUMERIC(5,2);

ALTER TABLE daily_sla_compliance
    ADD COLUMN IF NOT EXISTS avg_total_sitting_denver             NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_denver            NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_v1                 NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_v1                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_v2                 NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_v2                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er1                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er1               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er2                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er2               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er3                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er3               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er4                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er4               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er5                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er5               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_sitting_er6                NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_total_standing_er6               NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_v1           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_v1          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_v2           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_v2          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er1          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er1         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er2          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er2         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er3          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er3         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er4          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er4         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er5          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er5         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_sitting_er6          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_all_standing_er6         NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_denver           NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_denver          NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_v1               NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_v1              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_v2               NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_v2              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er1              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er1             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er2              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er2             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er3              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er3             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er4              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er4             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er5              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er5             NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_sitting_er6              NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS avg_percent_standing_er6             NUMERIC(5,2);
