-- Royalty titles + ruling colours: the two decorative identity fields
-- behind the leaderboard map, plus the display_name they compose into.
--
-- Both are CURATED LISTS with FK references, exactly like sql/025's
-- sfw_adjectives/emoji_nouns, and for the same two reasons: a rider
-- cannot type free text into a field that renders on a public map, and
-- the list can be extended by a later migration without a code change.
--
-- WHAT DISPLAY_NAME IS
-- --------------------
-- "King brave-owl-emoji" — the title, a space, then the existing
-- adjective+emoji public username. It is built from the PARTS
-- (royalty_title, username_adjective, username_emoji) and NOT from
-- public_username, because Postgres forbids a stored generated column
-- referencing another stored generated column. Same NULL propagation as
-- public_username: an account that has not been backfilled a username has
-- neither field.
--
-- display_name is deliberately NOT unique. public_username keeps its
-- uniqueness and remains the identity key; the title is decoration, and
-- two riders styling themselves King with different animals is fine.
--
-- WHY THE COLOUR PAIR IS UNIQUE AND THE COLOURS ARE NOT
-- -----------------------------------------------------
-- The leaderboard map colours each hexagon by whoever leads it. Two
-- riders whose territories render identically make that map unreadable
-- precisely where it is most interesting — adjacent cells. So the
-- (fill, border) PAIR is globally unique, which is 128 x 127 = 16 256
-- distinct claims rather than the 128 a unique fill alone would allow.
-- Riders may share a fill or share a border, just not both.
--
-- ALPHA governs the FILL only; the border renders opaque. A border whose
-- whole job is separating adjacent territories should not be able to fade
-- out. The 0.10 floor is for the same reason — a fully transparent
-- territory is an invisible one, and opting out of the map already has a
-- home in accounts.show_in_leaderboards.

CREATE TABLE IF NOT EXISTS royalty_titles (
    title       TEXT PRIMARY KEY,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ruling_colors (
    hex         TEXT PRIMARY KEY
                CONSTRAINT ruling_colors_hex_format
                CHECK (hex ~ '^#[0-9a-f]{6}$'),
    name        TEXT NOT NULL,          -- 'crimson-500'
    hue_family  TEXT NOT NULL,          -- picker grouping
    sort_order  INTEGER NOT NULL
);

-- Titles as specified by the operator, with three spellings corrected
-- (Emperror -> Emperor, Magesty -> Majesty, Emmissary -> Emissary).
--
-- Where the operator's list gave one half of a gendered pair, the other
-- half is seeded alongside it, and a neutral form is included wherever
-- English has one (Their Highness, Monarch, Sovereign, Noble). Nobody
-- should have to pick a gendered title to have a title at all. The
-- non-noble entries from the list (The Speediest, The Cool Dude, ...) are
-- kept verbatim — they are the ones with personality.
--
-- ON CONFLICT DO NOTHING so a later migration can extend this list, and
-- so re-running is safe.
INSERT INTO royalty_titles (title, sort_order) VALUES
    ('King', 10), ('Queen', 20), ('Monarch', 30),
    ('Emperor', 40), ('Empress', 50),
    ('Prince', 60), ('Princess', 70),
    ('Duke', 80), ('Duchess', 90),
    ('Baron', 100), ('Baroness', 110),
    ('Count', 120), ('Countess', 130),
    ('Sir', 140), ('Dame', 150), ('Noble', 160),
    ('His Highness', 170), ('Her Highness', 180), ('Their Highness', 190),
    ('His Majesty', 200), ('Her Majesty', 210), ('Majesty', 220),
    ('Sovereign', 230), ('Regent', 240),
    ('Reverend', 250), ('Honorable', 260), ('The Very Esteemed', 270),
    ('Emissary', 280), ('Ambassador', 290), ('Chancellor', 300),
    ('Humble Servant', 310),
    ('The Speediest', 320), ('The Cool Dude', 330), ('The Coolest', 340)
ON CONFLICT (title) DO NOTHING;

-- 128 colours: 16 hue families x 8 steps.
-- Generated by scripts/gen_ruling_palette.py — see that file for the method.
INSERT INTO ruling_colors (hex, name, hue_family, sort_order) VALUES
    ('#ffbfb8', 'red-100', 'red', 0),
    ('#f69b94', 'red-200', 'red', 1),
    ('#eb7770', 'red-300', 'red', 2),
    ('#da534f', 'red-400', 'red', 3),
    ('#c53637', 'red-500', 'red', 4),
    ('#a72629', 'red-600', 'red', 5),
    ('#831a1d', 'red-700', 'red', 6),
    ('#5f1113', 'red-800', 'red', 7),
    ('#fdbdca', 'crimson-100', 'crimson', 8),
    ('#f399ae', 'crimson-200', 'crimson', 9),
    ('#e77492', 'crimson-300', 'crimson', 10),
    ('#d55078', 'crimson-400', 'crimson', 11),
    ('#c13363', 'crimson-500', 'crimson', 12),
    ('#a32451', 'crimson-600', 'crimson', 13),
    ('#80183d', 'crimson-700', 'crimson', 14),
    ('#5d102b', 'crimson-800', 'crimson', 15),
    ('#f3bee1', 'magenta-100', 'magenta', 16),
    ('#e79bce', 'magenta-200', 'magenta', 17),
    ('#d978bb', 'magenta-300', 'magenta', 18),
    ('#c656a6', 'magenta-400', 'magenta', 19),
    ('#b13b92', 'magenta-500', 'magenta', 20),
    ('#962c7a', 'magenta-600', 'magenta', 21),
    ('#751e5f', 'magenta-700', 'magenta', 22),
    ('#551544', 'magenta-800', 'magenta', 23),
    ('#e4c3f3', 'purple-100', 'purple', 24),
    ('#d2a2e8', 'purple-200', 'purple', 25),
    ('#c081dc', 'purple-300', 'purple', 26),
    ('#ac61cb', 'purple-400', 'purple', 27),
    ('#9848b8', 'purple-500', 'purple', 28),
    ('#7f389c', 'purple-600', 'purple', 29),
    ('#63287a', 'purple-700', 'purple', 30),
    ('#471c58', 'purple-800', 'purple', 31),
    ('#d4c8fe', 'violet-100', 'violet', 32),
    ('#bca9f7', 'violet-200', 'violet', 33),
    ('#a68aee', 'violet-300', 'violet', 34),
    ('#8f6ce0', 'violet-400', 'violet', 35),
    ('#7c54cd', 'violet-500', 'violet', 36),
    ('#6742af', 'violet-600', 'violet', 37),
    ('#4f3189', 'violet-700', 'violet', 38),
    ('#382264', 'violet-800', 'violet', 39),
    ('#c3ceff', 'indigo-100', 'indigo', 40),
    ('#a3b2fe', 'indigo-200', 'indigo', 41),
    ('#8595f8', 'indigo-300', 'indigo', 42),
    ('#6b79ea', 'indigo-400', 'indigo', 43),
    ('#5761d8', 'indigo-500', 'indigo', 44),
    ('#464eb8', 'indigo-600', 'indigo', 45),
    ('#353b91', 'indigo-700', 'indigo', 46),
    ('#252a69', 'indigo-800', 'indigo', 47),
    ('#b3d4ff', 'blue-100', 'blue', 48),
    ('#87bafd', 'blue-200', 'blue', 49),
    ('#5ca0f6', 'blue-300', 'blue', 50),
    ('#3186e9', 'blue-400', 'blue', 51),
    ('#026fd7', 'blue-500', 'blue', 52),
    ('#005bb4', 'blue-600', 'blue', 53),
    ('#00468c', 'blue-700', 'blue', 54),
    ('#003167', 'blue-800', 'blue', 55),
    ('#a1dafc', 'sky-100', 'sky', 56),
    ('#6bc3f4', 'sky-200', 'sky', 57),
    ('#14abeb', 'sky-300', 'sky', 58),
    ('#0091c9', 'sky-400', 'sky', 59),
    ('#007bab', 'sky-500', 'sky', 60),
    ('#00658e', 'sky-600', 'sky', 61),
    ('#004e6f', 'sky-700', 'sky', 62),
    ('#003850', 'sky-800', 'sky', 63),
    ('#96dfec', 'cyan-100', 'cyan', 64),
    ('#51cade', 'cyan-200', 'cyan', 65),
    ('#00b2c8', 'cyan-300', 'cyan', 66),
    ('#0097aa', 'cyan-400', 'cyan', 67),
    ('#008090', 'cyan-500', 'cyan', 68),
    ('#006a77', 'cyan-600', 'cyan', 69),
    ('#00515c', 'cyan-700', 'cyan', 70),
    ('#003a42', 'cyan-800', 'cyan', 71),
    ('#96e1dc', 'teal-100', 'teal', 72),
    ('#51cec7', 'teal-200', 'teal', 73),
    ('#00b6af', 'teal-300', 'teal', 74),
    ('#009a94', 'teal-400', 'teal', 75),
    ('#00837e', 'teal-500', 'teal', 76),
    ('#006c68', 'teal-600', 'teal', 77),
    ('#005350', 'teal-700', 'teal', 78),
    ('#003c39', 'teal-800', 'teal', 79),
    ('#a3e1c5', 'emerald-100', 'emerald', 80),
    ('#6ccea6', 'emerald-200', 'emerald', 81),
    ('#0fba88', 'emerald-300', 'emerald', 82),
    ('#009e72', 'emerald-400', 'emerald', 83),
    ('#008660', 'emerald-500', 'emerald', 84),
    ('#006f4f', 'emerald-600', 'emerald', 85),
    ('#00563c', 'emerald-700', 'emerald', 86),
    ('#003d2a', 'emerald-800', 'emerald', 87),
    ('#b3dfb3', 'green-100', 'green', 88),
    ('#8aca8b', 'green-200', 'green', 89),
    ('#5eb663', 'green-300', 'green', 90),
    ('#2f9f3d', 'green-400', 'green', 91),
    ('#008a23', 'green-500', 'green', 92),
    ('#00721b', 'green-600', 'green', 93),
    ('#005813', 'green-700', 'green', 94),
    ('#003f0b', 'green-800', 'green', 95),
    ('#c6daa4', 'lime-100', 'lime', 96),
    ('#a7c474', 'lime-200', 'lime', 97),
    ('#8aad3d', 'lime-300', 'lime', 98),
    ('#719500', 'lime-400', 'lime', 99),
    ('#5f7e00', 'lime-500', 'lime', 100),
    ('#4e6800', 'lime-600', 'lime', 101),
    ('#3b5000', 'lime-700', 'lime', 102),
    ('#293900', 'lime-800', 'lime', 103),
    ('#dcd39a', 'yellow-100', 'yellow', 104),
    ('#c8b962', 'yellow-200', 'yellow', 105),
    ('#b49f03', 'yellow-300', 'yellow', 106),
    ('#998700', 'yellow-400', 'yellow', 107),
    ('#817200', 'yellow-500', 'yellow', 108),
    ('#6b5e00', 'yellow-600', 'yellow', 109),
    ('#524800', 'yellow-700', 'yellow', 110),
    ('#3b3300', 'yellow-800', 'yellow', 111),
    ('#eecb9a', 'amber-100', 'amber', 112),
    ('#e1ad63', 'amber-200', 'amber', 113),
    ('#d28f0e', 'amber-300', 'amber', 114),
    ('#b37900', 'amber-400', 'amber', 115),
    ('#986600', 'amber-500', 'amber', 116),
    ('#7e5400', 'amber-600', 'amber', 117),
    ('#624000', 'amber-700', 'amber', 118),
    ('#472d00', 'amber-800', 'amber', 119),
    ('#fac3a5', 'orange-100', 'orange', 120),
    ('#f0a276', 'orange-200', 'orange', 121),
    ('#e58042', 'orange-300', 'orange', 122),
    ('#d16100', 'orange-400', 'orange', 123),
    ('#b25200', 'orange-500', 'orange', 124),
    ('#944300', 'orange-600', 'orange', 125),
    ('#733200', 'orange-700', 'orange', 126),
    ('#532300', 'orange-800', 'orange', 127)
ON CONFLICT (hex) DO NOTHING;

ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS royalty_title       TEXT REFERENCES royalty_titles(title),
    ADD COLUMN IF NOT EXISTS ruling_color        TEXT REFERENCES ruling_colors(hex),
    ADD COLUMN IF NOT EXISTS ruling_border_color TEXT REFERENCES ruling_colors(hex),
    ADD COLUMN IF NOT EXISTS ruling_alpha        NUMERIC(3,2) NOT NULL DEFAULT 0.60
        CONSTRAINT accounts_ruling_alpha_range
        CHECK (ruling_alpha BETWEEN 0.10 AND 1.00);

-- Fill and border are set together or not at all, and must differ: a
-- border the same colour as its fill is not a border, and would silently
-- consume one of the 16 256 pair claims to render as a plain block.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'accounts_ruling_colors_coherent'
          AND conrelid = 'accounts'::regclass AND contype = 'c'
    ) THEN
        ALTER TABLE accounts
            ADD CONSTRAINT accounts_ruling_colors_coherent CHECK (
                (ruling_color IS NULL AND ruling_border_color IS NULL) OR
                (ruling_color IS NOT NULL AND ruling_border_color IS NOT NULL
                 AND ruling_color <> ruling_border_color)
            );
    END IF;
END $$;

-- The pair claim. Partial so the (NULL, NULL) accounts — every account
-- before it picks colours — do not contend for a single slot.
CREATE UNIQUE INDEX IF NOT EXISTS accounts_ruling_pair_key
    ON accounts (ruling_color, ruling_border_color)
    WHERE ruling_color IS NOT NULL AND ruling_border_color IS NOT NULL;

-- Title + existing public username. See the header for why this reads the
-- parts rather than public_username.
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS display_name TEXT
    GENERATED ALWAYS AS (
        COALESCE(royalty_title || ' ', '') || username_adjective || username_emoji
    ) STORED;
